version: "3.4"
############################
# STRICTLY FOR DEVELOPMENT #
############################
services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: df.dev
    command: ["yarn", "run", "start:dev"]
    environment:
      PORT: 8000
    volumes:
      - .:/user/src/app
    ports:
      - "8000:8000"
      - "5858:5858"
      - "9229:9229"
    depends_on:
      - postgres
  nginx:
    image: nginx:1.13
    ports:
      - "8080:8080"
    volumes:
      - ./web/public:/srv/www/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  postgres:
    container_name: postgres
    restart: always
    image: postgres:10.1
    ports:
      - "5432:5432"
    environment:
    - POSTGRES_DB=todo
    - POSTGRES_USER=testuser
    - POSTGRES_PASSWORD=example
    volumes:
      - ./postgres/data:/var/lib/postgresql
